import Header from '@/components/Header';
import Search from '@/components/Search';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${pretendard.className}`}>
        <div className="px-6">
          <div className="sticky top-0 z-10 bg-white">
            <Header />
            <Search />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
